name: Trigger Automation Tests

on:
  push:
    branches: [ main ]

jobs:
  notify-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch Event
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: ilmanarif/saucedemo-playwright-automation
          event_type: run-automation